language: node_js
node_js:
  - 8
before_install:
  - npm install gulp -g

script:
  - npm install
  - npm run build

cache:
  directories:
  - node_modules

notifications:
  email:
    - kyle@gotitapp.co